### ISSUE TITLE
Todo module polyglot-visualnode

### ISSUE THREAD

**Issue by cheramu** [cheramu/com.layers.polyglot-visualnode#3]
- [x] - @cheramu Make video tutorial/explain
- [ ] - @cheramu Rename prefix node["dialog"] = {}    → <axiom>[“node.dialog”] or other-name   def/define/data/n/d/a/?
- [ ] - Extract the 3d text as standalone ShiVa plugin
- [ ] - Make node.types more dynamic with union and configurable with filter
- [ ] - Make the node API' s more like ShiVa API
- [ ] - Do something use full with Stage   #4
- [ ] - Cleanup Stage view code
- [ ] - Make creation treeitem node easier and use it serveral places
- [ ] - Tree (RootView/LeafView)  is random saved (the order of keys can change with the same content)
- [ ] - Tree (RootView/LeafView) is stored in custom format
- [ ] - Tree (RootView/LeafView) are central and highly coupled
- [ ] - The script/export templates are not user friendly
- [ ] - The traverse script don't send "node" event for selected tree-item to listener.
- [ ] - Continue development packages
- [ ] - Linked nodes are not updated after editing a node #2 
- [ ] - Make pd-storage location in code config and usage in one place
- [ ] - Make folder pd-storage external path and packages in there own repo

...
