### ISSUE TITLE
Todo package polyglot-dialogue

### ISSUE THREAD

**Issue by cheramu** [cheramu/com.layers.polyglot-visualnode#5]
- [ ] -  make generation dialogue xml and lua implementation complete so it can be run directly form the game/editor api (preview).
- [ ] -  implement screenplay stage view
- [ ] -  implement translation editing, excel sheet import from shiva user with ready made translations ?

**Comment by cheramu** [comment]
- [ ] -  make generation dialogue xml and lua implementation complete so it can be run directly form the game/editor api (preview).



...
